### ISSUE TITLE
forbidden

### ISSUE THREAD

**Issue by pixelpaulaus** [centminmod/centminmod-gcc#1]
getting forbidden errors when trying to install v8+ , only working on v7

**Comment by centminmod** [comment]
Hi the scripts haven't really been maintained as they are only used for my Centmin Mod LEMP stack's nginx/php-fpm compatibility testing of GCC 7 and 8 and 9 at a time **before** CentOS YUM repos for CentOS SCL are not available. Once CentOS SCL YUM repos are available for GCC 7, 8 and 9 then these scripts aren't really used as then I update Centmin Mod to use GCC 7, 8 and 9 provided by CentOS SCL YUM repos.

When I have time the next update for scripts will be for GCC 10 prior to SCL repo official RPMs availability.

example of native CentOS SCL GCC 7, 8 and 9 via devtoolset-*-gcc packages and Clang 5.x via llvm-toolset packages

```
yum -q list installed devtoolset-7-gcc devtoolset-8-gcc devtoolset-9-gcc llvm-toolset-7-clang{*,-}* | tr -s ' ' | column -t
Installed                         Packages
devtoolset-7-gcc.x86_64           7.3.1-5.16.el7  @centos-sclo-rh
devtoolset-8-gcc.x86_64           8.3.1-3.2.el7   @centos-sclo-rh
devtoolset-9-gcc.x86_64           9.3.1-2.el7     @centos-sclo-rh
llvm-toolset-7-clang.x86_64       5.0.1-4.el7     @centos-sclo-rh
llvm-toolset-7-clang-libs.x86_64  5.0.1-4.el7     @centos-sclo-rh
```
```
nginx -V
nginx version: nginx/1.19.2 (220920-220921-centos7-0d688f1-br-25f86f0)
built by gcc 9.3.1 20200408 (Red Hat 9.3.1-2) (GCC) 
built with OpenSSL 1.1.1h  22 Sep 2020
TLS SNI support enabled
```
> configure arguments: --with-ld-opt='-Wl,-E -L/usr/local/zlib-cf/lib -L/usr/local/lib -ljemalloc -lpcre -Wl,-z,relro -Wl,-rpath,/usr/local/zlib-cf/lib:/usr/local/lib -flto=8 -fuse-ld=gold' --with-cc-opt='-I/usr/local/zlib-cf/include -I/usr/local/include -m64 -march=native -DTCP_FASTOPEN=23 -falign-functions=32 -g -O3 -Wno-error=strict-aliasing -fstack-protector-strong -flto=8 -fuse-ld=gold --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wno-error=pointer-sign -Wimplicit-fallthrough=0 -fcode-hoisting -Wp,-D_FORTIFY_SOURCE=2 -Wno-deprecated-declarations -gsplit-dwarf' --sbin-path=/usr/local/sbin/nginx --conf-path=/usr/local/nginx/conf/nginx.conf --build=220920-220921-centos7-0d688f1-br-25f86f0 --with-compat --with-http_stub_status_module --with-http_secure_link_module --with-http_flv_module --with-http_mp4_module --add-module=../nginx-rtmp-module --add-dynamic-module=../nginx-module-vts --with-libatomic --with-http_gzip_static_module --add-dynamic-module=../ngx_brotli --add-dynamic-module=../ngx_http_geoip2_module --with-http_sub_module --with-http_addition_module --with-http_image_filter_module=dynamic --with-http_geoip_module --with-stream_geoip_module --with-stream_realip_module --with-stream_ssl_preread_module --with-threads --with-stream --with-stream_ssl_module --with-http_slice_module --with-http_realip_module --add-dynamic-module=../ngx-fancyindex-0.4.2 --add-module=../ngx_cache_purge-2.5.1 --add-dynamic-module=../ngx_devel_kit-0.3.0 --add-dynamic-module=../set-misc-nginx-module-0.32 --add-dynamic-module=../echo-nginx-module-0.62 --add-module=../redis2-nginx-module-0.15 --add-module=../ngx_http_redis-0.3.7 --add-dynamic-module=../lua-nginx-module-0.10.17 --add-module=../memc-nginx-module-0.19 --add-module=../srcache-nginx-module-0.32 --add-dynamic-module=../headers-more-nginx-module-0.33 --with-pcre-jit --with-zlib=../zlib-cloudflare-1.3.0 --with-http_ssl_module --with-http_v2_module --with-http_v2_hpack_enc --with-openssl=../openssl-1.1.1h

As such you don't really need to use the script to compile GCC 7-9 if you have access to CentOS SCL YUM repo

**Comment by pixelpaulaus** [comment]
i am looking into using it as i am getting errors with node on my centmin server:
`Error: /lib64/libstdc++.so.6: version CXXABI_1.3.8 not found`
The annoying thing is, i have tried installing GCC7+ via so many methods, yet it always seems to revert back to 4.8.5
I have set all the possible variables in the centmin custom config. but none seem to get a higher GCC to install.
i have installed via `sudo yum install devtoolset-7` but after a restart it reverts back to 4.8.5, and still getting the CXXABI_1.3.8 error. this was a fresh CentOS7 and centminmod install i did last night too.

**Comment by centminmod** [comment]
Centmin Mod doesn't require you to use this gcc compile script at all, Centmin Mod 123.09beta01 and higher natively use CentOS SCL YUM repo's devtoolset-* GCC versions via persistent config variables outlined at https://community.centminmod.com/threads/guide-to-gcc-clang-compiler-selection-for-nginx-installs.13729/ and now default to GCC 8 out of the box with optional GCC 9

default set without setting in persistent config file /etc/centminmod/custom_config.inc is for GCC 8 defaults already in use
```
DEVTOOLSETSEVEN='n'
DEVTOOLSETEIGHT='y'
DEVTOOLSETNINE='n'
```
for GCC 9 change set in persistent config file /etc/centminmod/custom_config.inc
```
DEVTOOLSETSEVEN='n'
DEVTOOLSETEIGHT='n'
DEVTOOLSETNINE='y'
```
That is all you need to do and then recompile nginx and php-fpm via centmin.sh menu option 4 and 5

You might want to post on official Centmin Mod community forums at https://community.centminmod.com/forums/install-upgrades-or-pre-install-questions.8/ and provide info from nginx and php-fpm recompile logs when you run centmin.sh menu option 4 and 5 as outlined at 

* https://community.centminmod.com/threads/how-to-troubleshoot-nginx-installs-upgrades.17778/
* https://community.centminmod.com/threads/how-to-troubleshoot-php-installs-upgrades.17857/

**Comment by pixelpaulaus** [comment]
i have set those custom_config.inc settings and recompiled soooo many times, yet none seem to fix the issue of `Error: /lib64/libstdc++.so.6: version CXXABI_1.3.8 not found`

**Comment by centminmod** [comment]
Tried on fresh CentOS 7 install ? as the error could be related to running the gcc compiler scripts in this github repo.

Also what's output for

```
lscpu
```
and
```
cat /etc/centminmod/custom_config.inc
```
One common mistaken is having duplicate settings set i.e.

```
DEVTOOLSETSEVEN='n'
DEVTOOLSETEIGHT='n'
DEVTOOLSETNINE='y'
...othervariables...
...othervariables...
...othervariables...
...othervariables...
...othervariables...
DEVTOOLSETSEVEN='n'
DEVTOOLSETEIGHT='n'
DEVTOOLSETNINE='n'
```
The later duplicates would override the ones prior. In which GCC 7, 8 and 9 are disabled by duplicate settings. 

One reason enabling DEVTOOLSET variables won't work is if you disabled NGINX_DEVTOOLSETGCC='n' which defaults to enabled NGINX_DEVTOOLSETGCC='y' out of the box

But none should cause CXXABI errors usually.

But ultimately, only way I'd know what's up is with nginx and php-fpm upgrade/recompile logs as per
* https://community.centminmod.com/threads/how-to-troubleshoot-nginx-installs-upgrades.17778/
* https://community.centminmod.com/threads/how-to-troubleshoot-php-installs-upgrades.17857/

**Comment by pixelpaulaus** [comment]
lscpu:
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    1
Core(s) per socket:    4
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            15
Model:                 6
Model name:            Common KVM processor
Stepping:              1
CPU MHz:               3000.000
BogoMIPS:              6000.00
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              4096K
L3 cache:              16384K
NUMA node0 CPU(s):     0-3
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx lm constant_tsc nopl xtopology eagerfpu pni cx16 x2apic hypervisor lahf_lm


config:

#NGXDYNAMIC_BROTLI='y'
#NGINX_LIBBROTLI='y'
#NGINX_THREADS='y'
#LETSENCRYPT_DETECT='y'
#LIBRESSL_SWITCH='n'
#PHP_PGO='y'
#NGXDYNAMIC_NGXPAGESPEED='y'
#NGINX_PAGESPEED='y'

DEVTOOLSETSIX='n'
DEVTOOLSETSEVEN='n'
DEVTOOLSETEIGHT='n'




gcc -v:

[06:30][root@devenv.rack ~]# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC)

**Comment by pixelpaulaus** [comment]
the log output it to large to put up here.
I cant see any errors for GCC that stand out. anything i should look for?

**Comment by pixelpaulaus** [comment]
ok, i found a libstdc++.so.6.0.24 from that was built and moved it to the /usr/lib64 and linked /usr/lib64/libstdc++.so.6 to this new file. and it seems to work now.

**Comment by centminmod** [comment]
> ok, i found a libstdc++.so.6.0.24 from that was built and moved it to the /usr/lib64 and linked /usr/lib64/libstdc++.so.6 to this new file. and it seems to work now.

Just be careful as unintended consequences may come further down the track. Ideally just do a fresh CentOS 7 reload and reinstall 123.09beta01 and don't run this gcc compiler script and you should have a working system.

but yes if you set

```
DEVTOOLSETSIX='n'
DEVTOOLSETSEVEN='n'
DEVTOOLSETEIGHT='n'
```
Then GCC 4.8.5 will be used, the default is for DEVTOOLSETEIGHT='y' at least

**Comment by pixelpaulaus** [comment]
sorry i had: DEVTOOLSETEIGHT='y'

**Comment by pixelpaulaus** [comment]
so i have come back to this but still having issues...
I updated centmin package, and set my config as below. but still no 'CXXABI_1.3.8'

NGXDYNAMIC_BROTLI='y'
NGINX_LIBBROTLI='y'
NGINX_THREADS='y'
LETSENCRYPT_DETECT='y'
LIBRESSL_SWITCH='n'
PHP_PGO='y'
NGXDYNAMIC_NGXPAGESPEED='y'
NGINX_PAGESPEED='y'

MARCH_TARGETNATIVE='y'
DEVTOOLSETSEVEN='n'
DEVTOOLSETEIGHT='n'
DEVTOOLSETNINE='y'
CLANG='n'

i then do centmin option 4 and 5, followed by a restart.

[19:21][root@serv direct]# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC)

**Comment by centminmod** [comment]
> Just be careful as unintended consequences may come further down the track. Ideally just do a fresh CentOS 7 reload and reinstall 123.09beta01 and don't run this gcc compiler script and you should have a working system.

what issues ? the error `Error: /lib64/libstdc++.so.6: version CXXABI_1.3.8 not found` ?

Proper fix is to backup data and reload CentOS 7 OS fresh and do a fresh Centmin Mod install and DO NOT run this centminmod-gcc GCC compile routine as it isn't needed nor is it maintained or supported for GCC 7, 8, 9 after CentOS SCL Yum repos are available.

Also from your above lscpu output

> Flags: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx lm constant_tsc nopl xtopology eagerfpu pni cx16 x2apic hypervisor lahf_lm

you VPS virtual host virtualization isn't passing or supporting any of the cpu flags that would make beneficial use of higher GCC 7, 8 or 9 versions anyway in any meaningful way i.e. there are no listed cpu flag support for sse4_1, sse4_2, aes, avx, avx2 or pclmulqdq. So for best performance, you'd want to move to a VPS server which such support anyway.

here's an example of cpu with cpu flags with such support that would best take advantage of newer GCC versions

```
lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                1
On-line CPU(s) list:   0
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Xeon(R) Gold 6136 CPU @ 3.00GHz
Stepping:              4
CPU MHz:               2992.968
BogoMIPS:              5985.93
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              4096K
L3 cache:              16384K
NUMA node0 CPU(s):     0
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology eagerfpu pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 arat umip pku ospke spec_ctrl
```

or

```
lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                1
On-line CPU(s) list:   0
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             1
NUMA node(s):          1
Vendor ID:             AuthenticAMD
CPU family:            23
Model:                 49
Model name:            AMD EPYC 7542 32-Core Processor
Stepping:              0
CPU MHz:               2894.560
BogoMIPS:              5789.12
Hypervisor vendor:     KVM
Virtualization type:   full
NUMA node0 CPU(s):     0
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm art rep_good nopl extd_apicid eagerfpu pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw topoext perfctr_core retpoline_amd ssbd ibrs ibpb vmmcall fsgsbase tsc_adjust bmi1 avx2 smep bmi2 rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 arat umip spec_ctrl
```

**Comment by pixelpaulaus** [comment]
I actually wasn’t using this script.
Just the default centminmod, on a fresh install. And it did not work.

**Comment by centminmod** [comment]
On you mean Nginx wasn't compiled using GCC 9 and showed GCC 4.8.5 on a fresh Centmin Mod install ?  That is most likely due to Centmin Mod not detecting the appropriate supported cpu flags. To confirm if it's the case, you might want to post on official Centmin Mod community forums at https://community.centminmod.com/forums/install-upgrades-or-pre-install-questions.8/ and provide info from nginx and php-fpm recompile logs when you run centmin.sh menu option 4 and 5 as outlined at

* https://community.centminmod.com/threads/how-to-troubleshoot-nginx-installs-upgrades.17778/
* https://community.centminmod.com/threads/how-to-troubleshoot-php-installs-upgrades.17857/

These will allow us to figure out why Nginx and PHP-FPM compilations chose one GCC version over another

FYI, gcc version will also ways report 4.8.5 system version unless you check devtoolset versions in Centmin Mod

```
gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC) 
```
```
/opt/rh/devtoolset-8/root/usr/bin/gcc -v
Using built-in specs.
COLLECT_GCC=/opt/rh/devtoolset-8/root/usr/bin/gcc
COLLECT_LTO_WRAPPER=/opt/rh/devtoolset-8/root/usr/libexec/gcc/x86_64-redhat-linux/8/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,lto --prefix=/opt/rh/devtoolset-8/root/usr --mandir=/opt/rh/devtoolset-8/root/usr/share/man --infodir=/opt/rh/devtoolset-8/root/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --with-default-libstdcxx-abi=gcc4-compatible --enable-plugin --enable-initfini-array --with-isl=/builddir/build/BUILD/gcc-8.3.1-20190311/obj-x86_64-redhat-linux/isl-install --disable-libmpx --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 8.3.1 20190311 (Red Hat 8.3.1-3) (GCC) 
```
```
/opt/rh/devtoolset-9/root/usr/bin/gcc -v 
Using built-in specs.
COLLECT_GCC=/opt/rh/devtoolset-9/root/usr/bin/gcc
COLLECT_LTO_WRAPPER=/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,lto --prefix=/opt/rh/devtoolset-9/root/usr --mandir=/opt/rh/devtoolset-9/root/usr/share/man --infodir=/opt/rh/devtoolset-9/root/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --with-default-libstdcxx-abi=gcc4-compatible --enable-plugin --enable-initfini-array --with-isl=/builddir/build/BUILD/gcc-9.3.1-20200408/obj-x86_64-redhat-linux/isl-install --disable-libmpx --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 9.3.1 20200408 (Red Hat 9.3.1-2) (GCC) 
```
```
nginx -V
nginx version: nginx/1.19.3 (201020-135740-centos7-70a038f-br-9aec15e)
built by gcc 9.3.1 20200408 (Red Hat 9.3.1-2) (GCC) 
built with OpenSSL 1.1.1h  22 Sep 2020
TLS SNI support enabled
```

**Comment by centminmod** [comment]
Also see https://community.centminmod.com/threads/testing-gcc-8-gcc-9-clang-5-6-7-compiler-for-centmin-mod-nginx-php-fpm.13726/

**Comment by pixelpaulaus** [comment]
thanks, here is the lscpu on my latest VPS. should this be okay?


Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                2
On-line CPU(s) list:   0,1
Thread(s) per core:    2
Core(s) per socket:    1
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 94
Model name:            Intel Server Processor
Stepping:              3
CPU MHz:               3311.986
BogoMIPS:              6623.97
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              4096K
NUMA node0 CPU(s):     0,1
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx rdtscp lm constant_tsc arch_perfmon rep_good nopl eagerfpu pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb fsgsbase bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt xsaveopt xsavec xgetbv1 arat md_clear spec_ctrl

**Comment by pixelpaulaus** [comment]
okay, strange thing:
/opt/rh/devtoolset-9/root/usr/bin/gcc -v
reports: gcc version 9.3.1 20200408 (Red Hat 9.3.1-2) (GCC) 

and nginx -V
reports: built by gcc 9.3.1 20200408 (Red Hat 9.3.1-2) (GCC) 

so is it normal to still be getting the error:
/lib64/libstdc++.so.6: version CXXABI_1.3.8 not found ?

**Comment by centminmod** [comment]
> so is it normal to still be getting the error:
> /lib64/libstdc++.so.6: version CXXABI_1.3.8 not found ?

definitely not normal

would need info from nginx and php-fpm recompile logs when you run centmin.sh menu option 4 and 5 as outlined at

https://community.centminmod.com/threads/how-to-troubleshoot-nginx-installs-upgrades.17778/
https://community.centminmod.com/threads/how-to-troubleshoot-php-installs-upgrades.17857/

**Comment by pixelpaulaus** [comment]
the logs are huge, anything i should look for?

[centminmod_123.09beta01.b606_261020-190626_nginx_upgrade.log](https://github.com/centminmod/centminmod-gcc/files/5441495/centminmod_123.09beta01.b606_261020-190626_nginx_upgrade.log)
[centminmod_123.09beta01.b606_261020-192458_php_upgrade.log](https://github.com/centminmod/centminmod-gcc/files/5441496/centminmod_123.09beta01.b606_261020-192458_php_upgrade.log)

**Comment by centminmod** [comment]
Nginx upgrade log looks good. PHP upgrade log is rather empty - 

```
PHP Upgrade/Downgrade - Would you like to continue? [y/n] y

----------------------------------------------------------------
Install which version of PHP? (version i.e. 5.6.40, 7.0.33, NGDEBUG)
PHP 7.x/7.1.x/7.2.x/7.3.x is GA Stable but still may have broken PHP extensions.
NGDEBUG is PHP 8.0 dev builds minus incompatible PHP extensions
----------------------------------------------------------------

Current PHP Version: Warning:
Can Not Determine Latest PHP Version Installable: 

Enter PHP Version number you want to upgrade/downgrade to: 
```
it doesn't seem Centmin Mod could detect PHP version so is the CXXABI error with PHP-FPM ? what is output for

```
php -v
```
```
fpmrestart
```
and
```
nginx -V
```

**Comment by pixelpaulaus** [comment]
[08:56][root@serv ~]# php -v
PHP 7.3.14 (cli) (built: Oct 26 2020 19:39:36) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.14, Copyright (c) 1998-2018 Zend Technologies
    with the ionCube PHP Loader + ionCube24 v10.4.4, Copyright (c) 2002-2020, by ionCube Ltd.
    with Zend OPcache v7.3.14, Copyright (c) 1999-2018, by Zend Technologies

[08:56][root@serv ~]# fpmrestart
Restarting php-fpm (via systemctl) [  OK  ]


[08:57][root@serv ~]# nginx -V
nginx version: nginx/1.19.3 (261020-191019-centos7-kvm-5191982-br-9aec15e)
built by gcc 9.3.1 20200408 (Red Hat 9.3.1-2) (GCC) 
built with OpenSSL 1.1.1h  22 Sep 2020
TLS SNI support enabled
configure arguments: --with-ld-opt='-Wl,-E -L/usr/local/zlib-cf/lib -L/usr/local/lib -ljemalloc -Wl,-z,relro -Wl,-rpath,/usr/local/zlib-cf/lib:/usr/local/lib -flto=2 -fuse-ld=gold' --with-cc-opt='-I/usr/local/zlib-cf/include -I/usr/local/include -m64 -march=native -DTCP_FASTOPEN=23 -g -O3 -fstack-protector-strong -flto=2 -fuse-ld=gold --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wno-error=pointer-sign -Wimplicit-fallthrough=0 -fcode-hoisting -Wno-cast-function-type -Wno-format-extra-args -Wp,-D_FORTIFY_SOURCE=2 -Wno-deprecated-declarations' --sbin-path=/usr/local/sbin/nginx --conf-path=/usr/local/nginx/conf/nginx.conf --build=261020-191019-centos7-kvm-5191982-br-9aec15e --with-compat --with-http_stub_status_module --with-http_secure_link_module --with-libatomic --with-http_gzip_static_module --add-dynamic-module=../ngx_brotli --add-dynamic-module=../incubator-pagespeed-ngx-1.13.35.2-stable --with-http_sub_module --with-http_addition_module --with-http_image_filter_module=dynamic --with-http_geoip_module --with-stream_geoip_module --with-stream_realip_module --with-stream_ssl_preread_module --with-threads --with-stream --with-stream_ssl_module --with-http_realip_module --add-dynamic-module=../ngx-fancyindex-0.4.2 --add-module=../ngx_cache_purge-2.5.1 --add-dynamic-module=../ngx_devel_kit-0.3.0 --add-dynamic-module=../set-misc-nginx-module-0.32 --add-dynamic-module=../echo-nginx-module-0.62 --add-module=../redis2-nginx-module-0.15 --add-module=../ngx_http_redis-0.3.7 --add-module=../memc-nginx-module-0.19 --add-module=../srcache-nginx-module-0.32 --add-dynamic-module=../headers-more-nginx-module-0.33 --with-pcre-jit --with-zlib=../zlib-cloudflare-1.3.0 --with-http_ssl_module --with-http_v2_module --with-openssl=../openssl-1.1.1h --with-openssl-opt='enable-ec_nistp_64_gcc_128 enable-tls1_3 -fuse-ld=gold'

**Comment by pixelpaulaus** [comment]
i manually set the php version when i did it due to it not seeing the installed version.
I just checked option 5 now, and it is seeing it now.
So i am doing it again, and installing the latest version.
will give results shortly.

**Comment by pixelpaulaus** [comment]
new php upgrade...

**Comment by centminmod** [comment]
> Just the default centminmod, on a fresh install. And it did not work.

Not seeing anything wrong in PHP upgrade log either ? So what is not working? Exact error messages? And when do the errors display/occur ?

edit: I removed your PHP upgrade log as it contains the zend opcache admin stats page login details

**Comment by pixelpaulaus** [comment]
I get the error when trying to use argon2 in node.
Tho argon2 is working in php.

**Comment by centminmod** [comment]
nodeJS ? if so, I have no experience with nodeJS and argon2 so wouldn't know where to begin

**Comment by pixelpaulaus** [comment]
Should centmin be updating the /lib64/libstdc++.so.6 file?

**Comment by centminmod** [comment]
No Centmin Mod by default wouldn't touch it AFAIK.

What does output from these commands give

```
updatedb
locate libstdc++.so.6
```

actually it code be that nodeJS needs to be built against GCC 9 too ?? or https://stackoverflow.com/questions/49875588/importerror-lib64-libstdc-so-6-version-cxxabi-1-3-9-not-found

**Comment by pixelpaulaus** [comment]
[12:53][root@serv direct]# updatedb
[12:53][root@serv direct]# locate libstdc++.so.6
/usr/lib64/libstdc++.so.6
/usr/lib64/libstdc++.so.6.0.19
/usr/share/gdb/auto-load/usr/lib64/libstdc++.so.6.0.19-gdb.py
/usr/share/gdb/auto-load/usr/lib64/libstdc++.so.6.0.19-gdb.pyc
/usr/share/gdb/auto-load/usr/lib64/libstdc++.so.6.0.19-gdb.pyo
